/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CategoryManagement: typeof import('./src/components/admin/categories/CategoryManagement.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ForgotPassword: typeof import('./src/components/auth/ForgotPassword.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Login: typeof import('./src/components/auth/Login.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OrderManagement: typeof import('./src/components/admin/orders/OrderManagement.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProductDetail: typeof import('./src/components/admin/products/ProductDetail.vue')['default']
    ProductManagement: typeof import('./src/components/admin/products/ProductManagement.vue')['default']
    QuestionnaireDetail: typeof import('./src/components/user/QuestionnaireDetail.vue')['default']
    QuestionnaireManagement: typeof import('./src/components/user/QuestionnaireManagement.vue')['default']
    Register: typeof import('./src/components/auth/Register.vue')['default']
    Room: typeof import('./src/components/user/game/Room.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    SideBar: typeof import('./src/components/admin/SideBar.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SupplierManagement: typeof import('./src/components/admin/suppliers/SupplierManagement.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TheWelcome: typeof import('./src/components/home/TheWelcome.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UserManagement: typeof import('./src/components/admin/users/UserManagement.vue')['default']
    UserProfile: typeof import('./src/components/user/UserProfile.vue')['default']
    WaitingRoom: typeof import('./src/components/user/game/WaitingRoom.vue')['default']
  }
  export interface ComponentCustomProperties {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
